# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b0cd85bdcad66d57c5d468749249bdec76ccffc3293a728398350f90dbda3351a0345b45033c6bada2a1605cb226d3ed4350dc4d62448f60c6da46f0e0423082

test:
  secret_key_base: a682be79ea87c83a4c53e3bbb71ed187fb7902b2f0a17fd18284e3e1638240c5fdbe73e4e440580e72f65248c887c6f7fc17297f41ab3ecf7d0860c58337e208

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
